// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/interaccion.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConsultarEntrenadorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntrenadorId  string                 `protobuf:"bytes,1,opt,name=entrenador_id,json=entrenadorId,proto3" json:"entrenador_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsultarEntrenadorRequest) Reset() {
	*x = ConsultarEntrenadorRequest{}
	mi := &file_proto_interaccion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsultarEntrenadorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsultarEntrenadorRequest) ProtoMessage() {}

func (x *ConsultarEntrenadorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_interaccion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsultarEntrenadorRequest.ProtoReflect.Descriptor instead.
func (*ConsultarEntrenadorRequest) Descriptor() ([]byte, []int) {
	return file_proto_interaccion_proto_rawDescGZIP(), []int{0}
}

func (x *ConsultarEntrenadorRequest) GetEntrenadorId() string {
	if x != nil {
		return x.EntrenadorId
	}
	return ""
}

type ConsultarEntrenadorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nombre        string                 `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	Ranking       int32                  `protobuf:"varint,4,opt,name=ranking,proto3" json:"ranking,omitempty"`
	Estado        string                 `protobuf:"bytes,5,opt,name=estado,proto3" json:"estado,omitempty"`
	Suspension    int32                  `protobuf:"varint,6,opt,name=suspension,proto3" json:"suspension,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsultarEntrenadorResponse) Reset() {
	*x = ConsultarEntrenadorResponse{}
	mi := &file_proto_interaccion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsultarEntrenadorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsultarEntrenadorResponse) ProtoMessage() {}

func (x *ConsultarEntrenadorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_interaccion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsultarEntrenadorResponse.ProtoReflect.Descriptor instead.
func (*ConsultarEntrenadorResponse) Descriptor() ([]byte, []int) {
	return file_proto_interaccion_proto_rawDescGZIP(), []int{1}
}

func (x *ConsultarEntrenadorResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConsultarEntrenadorResponse) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *ConsultarEntrenadorResponse) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *ConsultarEntrenadorResponse) GetRanking() int32 {
	if x != nil {
		return x.Ranking
	}
	return 0
}

func (x *ConsultarEntrenadorResponse) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

func (x *ConsultarEntrenadorResponse) GetSuspension() int32 {
	if x != nil {
		return x.Suspension
	}
	return 0
}

type TorneosDisponiblesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TorneosDisponiblesRequest) Reset() {
	*x = TorneosDisponiblesRequest{}
	mi := &file_proto_interaccion_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TorneosDisponiblesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TorneosDisponiblesRequest) ProtoMessage() {}

func (x *TorneosDisponiblesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_interaccion_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TorneosDisponiblesRequest.ProtoReflect.Descriptor instead.
func (*TorneosDisponiblesRequest) Descriptor() ([]byte, []int) {
	return file_proto_interaccion_proto_rawDescGZIP(), []int{2}
}

type TorneosDisponiblesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Torneos       []*Torneo              `protobuf:"bytes,1,rep,name=torneos,proto3" json:"torneos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TorneosDisponiblesResponse) Reset() {
	*x = TorneosDisponiblesResponse{}
	mi := &file_proto_interaccion_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TorneosDisponiblesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TorneosDisponiblesResponse) ProtoMessage() {}

func (x *TorneosDisponiblesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_interaccion_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TorneosDisponiblesResponse.ProtoReflect.Descriptor instead.
func (*TorneosDisponiblesResponse) Descriptor() ([]byte, []int) {
	return file_proto_interaccion_proto_rawDescGZIP(), []int{3}
}

func (x *TorneosDisponiblesResponse) GetTorneos() []*Torneo {
	if x != nil {
		return x.Torneos
	}
	return nil
}

type Torneo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Torneo) Reset() {
	*x = Torneo{}
	mi := &file_proto_interaccion_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Torneo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Torneo) ProtoMessage() {}

func (x *Torneo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_interaccion_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Torneo.ProtoReflect.Descriptor instead.
func (*Torneo) Descriptor() ([]byte, []int) {
	return file_proto_interaccion_proto_rawDescGZIP(), []int{4}
}

func (x *Torneo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Torneo) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

type InscripcionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TorneoId      string                 `protobuf:"bytes,1,opt,name=torneo_id,json=torneoId,proto3" json:"torneo_id,omitempty"`
	EntrenadorId  string                 `protobuf:"bytes,2,opt,name=entrenador_id,json=entrenadorId,proto3" json:"entrenador_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InscripcionRequest) Reset() {
	*x = InscripcionRequest{}
	mi := &file_proto_interaccion_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InscripcionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InscripcionRequest) ProtoMessage() {}

func (x *InscripcionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_interaccion_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InscripcionRequest.ProtoReflect.Descriptor instead.
func (*InscripcionRequest) Descriptor() ([]byte, []int) {
	return file_proto_interaccion_proto_rawDescGZIP(), []int{5}
}

func (x *InscripcionRequest) GetTorneoId() string {
	if x != nil {
		return x.TorneoId
	}
	return ""
}

func (x *InscripcionRequest) GetEntrenadorId() string {
	if x != nil {
		return x.EntrenadorId
	}
	return ""
}

type InscripcionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inscripcion   string                 `protobuf:"bytes,1,opt,name=inscripcion,proto3" json:"inscripcion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InscripcionResponse) Reset() {
	*x = InscripcionResponse{}
	mi := &file_proto_interaccion_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InscripcionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InscripcionResponse) ProtoMessage() {}

func (x *InscripcionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_interaccion_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InscripcionResponse.ProtoReflect.Descriptor instead.
func (*InscripcionResponse) Descriptor() ([]byte, []int) {
	return file_proto_interaccion_proto_rawDescGZIP(), []int{6}
}

func (x *InscripcionResponse) GetInscripcion() string {
	if x != nil {
		return x.Inscripcion
	}
	return ""
}

var File_proto_interaccion_proto protoreflect.FileDescriptor

const file_proto_interaccion_proto_rawDesc = "" +
	"\n" +
	"\x17proto/interaccion.proto\x12\vinteraccion\"A\n" +
	"\x1aConsultarEntrenadorRequest\x12#\n" +
	"\rentrenador_id\x18\x01 \x01(\tR\fentrenadorId\"\xaf\x01\n" +
	"\x1bConsultarEntrenadorResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06nombre\x18\x02 \x01(\tR\x06nombre\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12\x18\n" +
	"\aranking\x18\x04 \x01(\x05R\aranking\x12\x16\n" +
	"\x06estado\x18\x05 \x01(\tR\x06estado\x12\x1e\n" +
	"\n" +
	"suspension\x18\x06 \x01(\x05R\n" +
	"suspension\"\x1b\n" +
	"\x19TorneosDisponiblesRequest\"K\n" +
	"\x1aTorneosDisponiblesResponse\x12-\n" +
	"\atorneos\x18\x01 \x03(\v2\x13.interaccion.TorneoR\atorneos\"0\n" +
	"\x06Torneo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\"V\n" +
	"\x12InscripcionRequest\x12\x1b\n" +
	"\ttorneo_id\x18\x01 \x01(\tR\btorneoId\x12#\n" +
	"\rentrenador_id\x18\x02 \x01(\tR\fentrenadorId\"7\n" +
	"\x13InscripcionResponse\x12 \n" +
	"\vinscripcion\x18\x01 \x01(\tR\vinscripcion2\xc0\x02\n" +
	"\n" +
	"LcpService\x12h\n" +
	"\x13ConsultarEntrenador\x12'.interaccion.ConsultarEntrenadorRequest\x1a(.interaccion.ConsultarEntrenadorResponse\x12n\n" +
	"\x1bConsultarTorneosDisponibles\x12&.interaccion.TorneosDisponiblesRequest\x1a'.interaccion.TorneosDisponiblesResponse\x12X\n" +
	"\x13InscribirseEnTorneo\x12\x1f.interaccion.InscripcionRequest\x1a .interaccion.InscripcionResponseB\x13Z\x11grpc-server/protob\x06proto3"

var (
	file_proto_interaccion_proto_rawDescOnce sync.Once
	file_proto_interaccion_proto_rawDescData []byte
)

func file_proto_interaccion_proto_rawDescGZIP() []byte {
	file_proto_interaccion_proto_rawDescOnce.Do(func() {
		file_proto_interaccion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_interaccion_proto_rawDesc), len(file_proto_interaccion_proto_rawDesc)))
	})
	return file_proto_interaccion_proto_rawDescData
}

var file_proto_interaccion_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_interaccion_proto_goTypes = []any{
	(*ConsultarEntrenadorRequest)(nil),  // 0: interaccion.ConsultarEntrenadorRequest
	(*ConsultarEntrenadorResponse)(nil), // 1: interaccion.ConsultarEntrenadorResponse
	(*TorneosDisponiblesRequest)(nil),   // 2: interaccion.TorneosDisponiblesRequest
	(*TorneosDisponiblesResponse)(nil),  // 3: interaccion.TorneosDisponiblesResponse
	(*Torneo)(nil),                      // 4: interaccion.Torneo
	(*InscripcionRequest)(nil),          // 5: interaccion.InscripcionRequest
	(*InscripcionResponse)(nil),         // 6: interaccion.InscripcionResponse
}
var file_proto_interaccion_proto_depIdxs = []int32{
	4, // 0: interaccion.TorneosDisponiblesResponse.torneos:type_name -> interaccion.Torneo
	0, // 1: interaccion.LcpService.ConsultarEntrenador:input_type -> interaccion.ConsultarEntrenadorRequest
	2, // 2: interaccion.LcpService.ConsultarTorneosDisponibles:input_type -> interaccion.TorneosDisponiblesRequest
	5, // 3: interaccion.LcpService.InscribirseEnTorneo:input_type -> interaccion.InscripcionRequest
	1, // 4: interaccion.LcpService.ConsultarEntrenador:output_type -> interaccion.ConsultarEntrenadorResponse
	3, // 5: interaccion.LcpService.ConsultarTorneosDisponibles:output_type -> interaccion.TorneosDisponiblesResponse
	6, // 6: interaccion.LcpService.InscribirseEnTorneo:output_type -> interaccion.InscripcionResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_interaccion_proto_init() }
func file_proto_interaccion_proto_init() {
	if File_proto_interaccion_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_interaccion_proto_rawDesc), len(file_proto_interaccion_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_interaccion_proto_goTypes,
		DependencyIndexes: file_proto_interaccion_proto_depIdxs,
		MessageInfos:      file_proto_interaccion_proto_msgTypes,
	}.Build()
	File_proto_interaccion_proto = out.File
	file_proto_interaccion_proto_goTypes = nil
	file_proto_interaccion_proto_depIdxs = nil
}
