// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: proto/interaccion.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GimService_AsignarCombate_FullMethodName = "/interaccion.GimService/AsignarCombate"
)

// GimServiceClient is the client API for GimService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GimServiceClient interface {
	AsignarCombate(ctx context.Context, in *AsignacionCombateRequest, opts ...grpc.CallOption) (*AsignacionCombateResponse, error)
}

type gimServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGimServiceClient(cc grpc.ClientConnInterface) GimServiceClient {
	return &gimServiceClient{cc}
}

func (c *gimServiceClient) AsignarCombate(ctx context.Context, in *AsignacionCombateRequest, opts ...grpc.CallOption) (*AsignacionCombateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AsignacionCombateResponse)
	err := c.cc.Invoke(ctx, GimService_AsignarCombate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GimServiceServer is the server API for GimService service.
// All implementations must embed UnimplementedGimServiceServer
// for forward compatibility.
type GimServiceServer interface {
	AsignarCombate(context.Context, *AsignacionCombateRequest) (*AsignacionCombateResponse, error)
	mustEmbedUnimplementedGimServiceServer()
}

// UnimplementedGimServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGimServiceServer struct{}

func (UnimplementedGimServiceServer) AsignarCombate(context.Context, *AsignacionCombateRequest) (*AsignacionCombateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AsignarCombate not implemented")
}
func (UnimplementedGimServiceServer) mustEmbedUnimplementedGimServiceServer() {}
func (UnimplementedGimServiceServer) testEmbeddedByValue()                    {}

// UnsafeGimServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GimServiceServer will
// result in compilation errors.
type UnsafeGimServiceServer interface {
	mustEmbedUnimplementedGimServiceServer()
}

func RegisterGimServiceServer(s grpc.ServiceRegistrar, srv GimServiceServer) {
	// If the following call pancis, it indicates UnimplementedGimServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GimService_ServiceDesc, srv)
}

func _GimService_AsignarCombate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AsignacionCombateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GimServiceServer).AsignarCombate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GimService_AsignarCombate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GimServiceServer).AsignarCombate(ctx, req.(*AsignacionCombateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GimService_ServiceDesc is the grpc.ServiceDesc for GimService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GimService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "interaccion.GimService",
	HandlerType: (*GimServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AsignarCombate",
			Handler:    _GimService_AsignarCombate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/interaccion.proto",
}
