// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/interaccion.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AsignacionCombateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CombateId     string                 `protobuf:"bytes,1,opt,name=combate_id,json=combateId,proto3" json:"combate_id,omitempty"`
	TorneoId      string                 `protobuf:"bytes,2,opt,name=torneo_id,json=torneoId,proto3" json:"torneo_id,omitempty"`
	Entrenador_1  *EntrenadorCombate     `protobuf:"bytes,3,opt,name=entrenador_1,json=entrenador1,proto3" json:"entrenador_1,omitempty"`
	Entrenador_2  *EntrenadorCombate     `protobuf:"bytes,4,opt,name=entrenador_2,json=entrenador2,proto3" json:"entrenador_2,omitempty"`
	Region        string                 `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AsignacionCombateRequest) Reset() {
	*x = AsignacionCombateRequest{}
	mi := &file_proto_interaccion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AsignacionCombateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsignacionCombateRequest) ProtoMessage() {}

func (x *AsignacionCombateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_interaccion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsignacionCombateRequest.ProtoReflect.Descriptor instead.
func (*AsignacionCombateRequest) Descriptor() ([]byte, []int) {
	return file_proto_interaccion_proto_rawDescGZIP(), []int{0}
}

func (x *AsignacionCombateRequest) GetCombateId() string {
	if x != nil {
		return x.CombateId
	}
	return ""
}

func (x *AsignacionCombateRequest) GetTorneoId() string {
	if x != nil {
		return x.TorneoId
	}
	return ""
}

func (x *AsignacionCombateRequest) GetEntrenador_1() *EntrenadorCombate {
	if x != nil {
		return x.Entrenador_1
	}
	return nil
}

func (x *AsignacionCombateRequest) GetEntrenador_2() *EntrenadorCombate {
	if x != nil {
		return x.Entrenador_2
	}
	return nil
}

func (x *AsignacionCombateRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

type EntrenadorCombate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nombre        string                 `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Ranking       int32                  `protobuf:"varint,3,opt,name=ranking,proto3" json:"ranking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntrenadorCombate) Reset() {
	*x = EntrenadorCombate{}
	mi := &file_proto_interaccion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntrenadorCombate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntrenadorCombate) ProtoMessage() {}

func (x *EntrenadorCombate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_interaccion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntrenadorCombate.ProtoReflect.Descriptor instead.
func (*EntrenadorCombate) Descriptor() ([]byte, []int) {
	return file_proto_interaccion_proto_rawDescGZIP(), []int{1}
}

func (x *EntrenadorCombate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EntrenadorCombate) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *EntrenadorCombate) GetRanking() int32 {
	if x != nil {
		return x.Ranking
	}
	return 0
}

type AsignacionCombateResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TorneoId           string                 `protobuf:"bytes,1,opt,name=torneo_id,json=torneoId,proto3" json:"torneo_id,omitempty"`
	IdEntrenador_1     string                 `protobuf:"bytes,2,opt,name=id_entrenador_1,json=idEntrenador1,proto3" json:"id_entrenador_1,omitempty"`
	NombreEntrenador_1 string                 `protobuf:"bytes,3,opt,name=nombre_entrenador_1,json=nombreEntrenador1,proto3" json:"nombre_entrenador_1,omitempty"`
	IdEntrenador_2     string                 `protobuf:"bytes,4,opt,name=id_entrenador_2,json=idEntrenador2,proto3" json:"id_entrenador_2,omitempty"`
	NombreEntrenador_2 string                 `protobuf:"bytes,5,opt,name=nombre_entrenador_2,json=nombreEntrenador2,proto3" json:"nombre_entrenador_2,omitempty"`
	IdGanador          string                 `protobuf:"bytes,6,opt,name=id_ganador,json=idGanador,proto3" json:"id_ganador,omitempty"`
	NombreGanador      string                 `protobuf:"bytes,7,opt,name=nombre_ganador,json=nombreGanador,proto3" json:"nombre_ganador,omitempty"`
	Fecha              string                 `protobuf:"bytes,8,opt,name=fecha,proto3" json:"fecha,omitempty"`
	TipoMensaje        string                 `protobuf:"bytes,9,opt,name=tipo_mensaje,json=tipoMensaje,proto3" json:"tipo_mensaje,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AsignacionCombateResponse) Reset() {
	*x = AsignacionCombateResponse{}
	mi := &file_proto_interaccion_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AsignacionCombateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsignacionCombateResponse) ProtoMessage() {}

func (x *AsignacionCombateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_interaccion_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsignacionCombateResponse.ProtoReflect.Descriptor instead.
func (*AsignacionCombateResponse) Descriptor() ([]byte, []int) {
	return file_proto_interaccion_proto_rawDescGZIP(), []int{2}
}

func (x *AsignacionCombateResponse) GetTorneoId() string {
	if x != nil {
		return x.TorneoId
	}
	return ""
}

func (x *AsignacionCombateResponse) GetIdEntrenador_1() string {
	if x != nil {
		return x.IdEntrenador_1
	}
	return ""
}

func (x *AsignacionCombateResponse) GetNombreEntrenador_1() string {
	if x != nil {
		return x.NombreEntrenador_1
	}
	return ""
}

func (x *AsignacionCombateResponse) GetIdEntrenador_2() string {
	if x != nil {
		return x.IdEntrenador_2
	}
	return ""
}

func (x *AsignacionCombateResponse) GetNombreEntrenador_2() string {
	if x != nil {
		return x.NombreEntrenador_2
	}
	return ""
}

func (x *AsignacionCombateResponse) GetIdGanador() string {
	if x != nil {
		return x.IdGanador
	}
	return ""
}

func (x *AsignacionCombateResponse) GetNombreGanador() string {
	if x != nil {
		return x.NombreGanador
	}
	return ""
}

func (x *AsignacionCombateResponse) GetFecha() string {
	if x != nil {
		return x.Fecha
	}
	return ""
}

func (x *AsignacionCombateResponse) GetTipoMensaje() string {
	if x != nil {
		return x.TipoMensaje
	}
	return ""
}

var File_proto_interaccion_proto protoreflect.FileDescriptor

const file_proto_interaccion_proto_rawDesc = "" +
	"\n" +
	"\x17proto/interaccion.proto\x12\vinteraccion\"\xf4\x01\n" +
	"\x18AsignacionCombateRequest\x12\x1d\n" +
	"\n" +
	"combate_id\x18\x01 \x01(\tR\tcombateId\x12\x1b\n" +
	"\ttorneo_id\x18\x02 \x01(\tR\btorneoId\x12A\n" +
	"\fentrenador_1\x18\x03 \x01(\v2\x1e.interaccion.EntrenadorCombateR\ventrenador1\x12A\n" +
	"\fentrenador_2\x18\x04 \x01(\v2\x1e.interaccion.EntrenadorCombateR\ventrenador2\x12\x16\n" +
	"\x06region\x18\x05 \x01(\tR\x06region\"U\n" +
	"\x11EntrenadorCombate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06nombre\x18\x02 \x01(\tR\x06nombre\x12\x18\n" +
	"\aranking\x18\x03 \x01(\x05R\aranking\"\xe7\x02\n" +
	"\x19AsignacionCombateResponse\x12\x1b\n" +
	"\ttorneo_id\x18\x01 \x01(\tR\btorneoId\x12&\n" +
	"\x0fid_entrenador_1\x18\x02 \x01(\tR\ridEntrenador1\x12.\n" +
	"\x13nombre_entrenador_1\x18\x03 \x01(\tR\x11nombreEntrenador1\x12&\n" +
	"\x0fid_entrenador_2\x18\x04 \x01(\tR\ridEntrenador2\x12.\n" +
	"\x13nombre_entrenador_2\x18\x05 \x01(\tR\x11nombreEntrenador2\x12\x1d\n" +
	"\n" +
	"id_ganador\x18\x06 \x01(\tR\tidGanador\x12%\n" +
	"\x0enombre_ganador\x18\a \x01(\tR\rnombreGanador\x12\x14\n" +
	"\x05fecha\x18\b \x01(\tR\x05fecha\x12!\n" +
	"\ftipo_mensaje\x18\t \x01(\tR\vtipoMensaje2m\n" +
	"\n" +
	"GimService\x12_\n" +
	"\x0eAsignarCombate\x12%.interaccion.AsignacionCombateRequest\x1a&.interaccion.AsignacionCombateResponseB\x13Z\x11grpc-server/protob\x06proto3"

var (
	file_proto_interaccion_proto_rawDescOnce sync.Once
	file_proto_interaccion_proto_rawDescData []byte
)

func file_proto_interaccion_proto_rawDescGZIP() []byte {
	file_proto_interaccion_proto_rawDescOnce.Do(func() {
		file_proto_interaccion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_interaccion_proto_rawDesc), len(file_proto_interaccion_proto_rawDesc)))
	})
	return file_proto_interaccion_proto_rawDescData
}

var file_proto_interaccion_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_interaccion_proto_goTypes = []any{
	(*AsignacionCombateRequest)(nil),  // 0: interaccion.AsignacionCombateRequest
	(*EntrenadorCombate)(nil),         // 1: interaccion.EntrenadorCombate
	(*AsignacionCombateResponse)(nil), // 2: interaccion.AsignacionCombateResponse
}
var file_proto_interaccion_proto_depIdxs = []int32{
	1, // 0: interaccion.AsignacionCombateRequest.entrenador_1:type_name -> interaccion.EntrenadorCombate
	1, // 1: interaccion.AsignacionCombateRequest.entrenador_2:type_name -> interaccion.EntrenadorCombate
	0, // 2: interaccion.GimService.AsignarCombate:input_type -> interaccion.AsignacionCombateRequest
	2, // 3: interaccion.GimService.AsignarCombate:output_type -> interaccion.AsignacionCombateResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_interaccion_proto_init() }
func file_proto_interaccion_proto_init() {
	if File_proto_interaccion_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_interaccion_proto_rawDesc), len(file_proto_interaccion_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_interaccion_proto_goTypes,
		DependencyIndexes: file_proto_interaccion_proto_depIdxs,
		MessageInfos:      file_proto_interaccion_proto_msgTypes,
	}.Build()
	File_proto_interaccion_proto = out.File
	file_proto_interaccion_proto_goTypes = nil
	file_proto_interaccion_proto_depIdxs = nil
}
